// <auto-generated />
using System;
using CupApplication.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CupApplication.Migrations
{
    [DbContext(typeof(AppDBContent))]
    partial class AppDBContentModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CupApplication.Data.Models.Beneficiaries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GroupObjId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GroupObjId");

                    b.ToTable("DB_Beneficiaries");
                });

            modelBuilder.Entity("CupApplication.Data.Models.BenefitType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Koefficient")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("DB_BenefitType");
                });

            modelBuilder.Entity("CupApplication.Data.Models.Drinks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Source1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DB_Drinks");
                });

            modelBuilder.Entity("CupApplication.Data.Models.Drinks_leftovers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Amount")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("DB_Drinks_leftovers");
                });

            modelBuilder.Entity("CupApplication.Data.Models.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("PortionPrice")
                        .HasColumnType("real");

                    b.Property<float>("PortionVolume")
                        .HasColumnType("real");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<float>("VolumeInStock")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("DB_Products");
                });

            modelBuilder.Entity("CupApplication.Data.Models.Sales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BeneficiariID")
                        .HasColumnType("int");

                    b.Property<int?>("Cup1_Amount")
                        .HasColumnType("int");

                    b.Property<int?>("Cup1_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Cup2_Amount")
                        .HasColumnType("int");

                    b.Property<int?>("Cup2_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Cup3_Amount")
                        .HasColumnType("int");

                    b.Property<int?>("Cup3_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Cup4_Amount")
                        .HasColumnType("int");

                    b.Property<int?>("Cup4_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Cup5_Amount")
                        .HasColumnType("int");

                    b.Property<int?>("Cup5_ID")
                        .HasColumnType("int");

                    b.Property<float?>("Paid")
                        .HasColumnType("real");

                    b.Property<int?>("Product1_Amount")
                        .HasColumnType("int");

                    b.Property<int?>("Product1_ID")
                        .HasColumnType("int");

                    b.Property<int?>("Product2_Amount")
                        .HasColumnType("int");

                    b.Property<int?>("Product2_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.Property<int>("WorkingTimeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DB_Sales");
                });

            modelBuilder.Entity("CupApplication.Data.Models.WorkingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CloseTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpenTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SessionGuid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkerID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DB_WorkingSession");
                });

            modelBuilder.Entity("CupApplication.Data.Models.Beneficiaries", b =>
                {
                    b.HasOne("CupApplication.Data.Models.BenefitType", "GroupObj")
                        .WithMany("Persons")
                        .HasForeignKey("GroupObjId");

                    b.Navigation("GroupObj");
                });

            modelBuilder.Entity("CupApplication.Data.Models.BenefitType", b =>
                {
                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
